### ISSUE TITLE
Release 4.0.1 not published to Maven Central

### ISSUE THREAD

**Issue by klauss42** [xdev-software/vaadin-date-range-picker#260]
Is this intended that the latest release is not published?
Maybe related: https://github.com/xdev-software/vaadin-date-range-picker/actions/runs/6107939550

**Comment by AB-xdev** [comment]
@klauss42 
Oh you are correct. Thank you for noting that. 
Looks like Maven Central had the usual problems of not working.
I will rerun the release.

**Comment by AB-xdev** [comment]
Should be fixed now
