### ISSUE TITLE
I18n problems

### ISSUE THREAD

**Issue by Dudeplayz** [xdev-software/vaadin-date-range-picker#27]
Hi XDEV,
I have tested today your component. First of all, it's great!

But while developing I discovered some problems with translating the component:

1. If I apply another dateRangeLocalizerFunction, it is never called. The set of the LabelGenerator is called in `initUI` of DateRangePickerOverlay, which is called on constructor invocation. So the change afterward doesn't have any effect.
https://github.com/xdev-software/vaadin-date-range-picker/blob/06fb52662d2f944b1c26aa0ff122cc3fc4c45a0a/vaadin-date-range-picker/src/main/java/software/xdev/vaadin/daterange_picker/ui/DateRangePickerOverlay.java#L95

It should be applied like the translation for the DatePickers in the `AttachEvent`.
I could create a pull request for this.

2. I think there could be a more uniform way to access the labels of the DatePickers and the Combobox. This is only a suggestion. I discovered these while using this component. Some documentation/tutorial could also help here.

I am also from Germany, so we could communicate in german. Feel free to contact me.

Best regards,
Dario

**Comment by AB-xdev** [comment]
Hi Dario,

thanks for your feedback.

I created a fix with #29 which should improve the I18N handling of the date-range-picker

**Comment by Dudeplayz** [comment]
Looks good 👍.
