### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by Dudeplayz** [xdev-software/vaadin-date-range-picker#30]
Hey,
While working with the component I discovered some typos. I am not sure If there are more of them, but it should be checked:
- Model is spelled with only one L in English.
https://github.com/xdev-software/vaadin-date-range-picker/blob/06fb52662d2f944b1c26aa0ff122cc3fc4c45a0a/vaadin-date-range-picker/src/main/java/software/xdev/vaadin/daterange_picker/buisness/DateRangeModell.java#L33
- Missing T for settable (variable is named correctly)
https://github.com/xdev-software/vaadin-date-range-picker/blob/06fb52662d2f944b1c26aa0ff122cc3fc4c45a0a/vaadin-date-range-picker/src/main/java/software/xdev/vaadin/daterange_picker/buisness/AbstractDateRange.java#L108

**Comment by Dudeplayz** [comment]
I also think `defaultDescription` should be written out:
https://github.com/xdev-software/vaadin-date-range-picker/blob/06fb52662d2f944b1c26aa0ff122cc3fc4c45a0a/vaadin-date-range-picker/src/main/java/software/xdev/vaadin/daterange_picker/buisness/DateRange.java#L45

**Comment by Dudeplayz** [comment]
Maybe use a spellchecker IDE plugin.

**Comment by AB-xdev** [comment]
@Dudeplayz 

at first a very big thanks for your great reviews and suggestions for improvements :+1:

Seems like I overlooked some of these misspellings, the component was originally only used in a german speaking project and later extracted to GitHub. 
I will fix them soon :)

We will also check/review the other issues as soon, as we have time.
