### ISSUE TITLE
Change method signature for setting the DateRange

### ISSUE THREAD

**Issue by Dudeplayz** [xdev-software/vaadin-date-range-picker#32]
Hey,
I was searching for a way to set the default DateRange. With the way, I was thinking, I ended up with getting the current model and setting the DateRange to it. Now I was digging through the code and saw the method which (I think) is meant to be used for this `setModellForTodayAndByDateRange`. The first time I saw this method, it was curious to me. I would simply name the method 'setDateRange' and maybe overload it with a version to supply the LocalDate by yourself. The explanation should be done with some JavaDoc.

A faster accessor for the current DateRange would be also nice. So you can call it simply at the DateRangePicker to get the current value. In general, it may make sense to pass through the accessor methods of the model. It's just an idea, I am happy to discuss this.

https://github.com/xdev-software/vaadin-date-range-picker/blob/06fb52662d2f944b1c26aa0ff122cc3fc4c45a0a/vaadin-date-range-picker/src/main/java/software/xdev/vaadin/daterange_picker/ui/DateRangePicker.java#L357-L361

**Comment by AB-xdev** [comment]
Fix for the first paragraph is already on the way 😄 

For paragraph No2:
>A faster accessor for the current DateRange would be also nice. So you can call it simply at the DateRangePicker to get the current value. In general, it may make sense to pass through the accessor methods of the model.

This is already done [here](https://github.com/xdev-software/vaadin-date-range-picker/blob/develop/vaadin-date-range-picker/src/main/java/software/xdev/vaadin/daterange_picker/ui/DateRangePicker.java#L450-L490)
Or am I getting something wrong?

**Comment by Dudeplayz** [comment]
@AB-xdev
Sorry for the late reply. Yes, it is the function I meant.
