### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by Dudeplayz** [xdev-software/vaadin-date-range-picker#33]
Hey,
The dark theme support for lumo seems to be broken:

![image](https://user-images.githubusercontent.com/15174076/96607160-5d36e480-12f8-11eb-83f3-edd346816820.png)

**Comment by AB-xdev** [comment]
The styles in https://github.com/xdev-software/vaadin-date-range-picker/blob/develop/vaadin-date-range-picker/src/main/resources/META-INF/resources/frontend/styles/dateRangePicker.css need to be adjusted
