### ISSUE TITLE
Overlay is not overlayed

### ISSUE THREAD

**Issue by Dudeplayz** [xdev-software/vaadin-date-range-picker#352]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/xdev-software/vaadin-date-range-picker/releases/latest)
- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/vaadin-date-range-picker/issues) or [closed](https://github.com/xdev-software/vaadin-date-range-picker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

4.1.0

### Steps to reproduce the bug

Take a DateRangePicker and content after it. Open it and the layout should change.

### Expected behavior

<img width="602" alt="CleanShot 2024-08-02 at 22 45 32@2x" src="https://github.com/user-attachments/assets/f3aab53d-67dd-4342-8435-7d9980fffee1">

The overlay should be an actual overlay like in previous versions.

### Actual behavior

<img width="583" alt="CleanShot 2024-08-02 at 22 45 04@2x" src="https://github.com/user-attachments/assets/e58d1288-420b-4f06-8762-6d2c3cf87d10">

The overlay extends the size of the component.

### Additional information

vaadin 24.4.7

**Comment by AB-xdev** [comment]
Hmm I couldn't reproduce this in our demo:

![](https://github.com/user-attachments/assets/02619ab6-b350-4903-b419-50464bfb40fc)

Are the CSS classes applied correctly? It should look like this:
![](https://github.com/user-attachments/assets/64e42585-94a2-4554-9e49-07e56916caa7)

**Comment by Dudeplayz** [comment]
Seems like these are not applied 🤔
<img width="1173" alt="CleanShot 2024-08-05 at 13 40 36@2x" src="https://github.com/user-attachments/assets/d5ec873d-279d-471b-99c4-2e9d317d7193">

**Comment by AB-xdev** [comment]
Hmm I see the css classes on the element but are they also listed in the "styles" section on the right side of the devtools?
![](https://github.com/user-attachments/assets/7d420728-4812-4860-8d24-6ff13a3edd79)

If they are missing it likely indicates that something went wrong during resolution of frontend resources...

We use the same component in one of our apps and it works without any problems ^^

**Comment by AB-xdev** [comment]
> Maybe you like to build a jandex natively into your addon?

I don't think we should currently do this as
* we don't see a lot of Quarkus usage
* the index will increase the JAR size and will be useless for e.g. Spring users as Spring uses a different indexing process

Maybe we can do a release variant (e.g. ``1.2.3-quarkus``) in the future but for now I don't think it's worth it.

> Sorry and thanks for the effort, because of my configuration failure!

No problem :)
