### ISSUE TITLE
FormatLocale is not applied correctly to the overlay button

### ISSUE THREAD

**Issue by Dudeplayz** [xdev-software/vaadin-date-range-picker#353]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/xdev-software/vaadin-date-range-picker/releases/latest)
- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/vaadin-date-range-picker/issues) or [closed](https://github.com/xdev-software/vaadin-date-range-picker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected version

4.1.0

### Steps to reproduce the bug

```kotlin
    fun getDateRangePicker(items: List<SimpleDateRange> = SimpleDateRanges.allValues().toMutableList()): DateRangePicker<SimpleDateRange> =
            DateRangePicker(buildDateRangeModel(), items)
                .withDatePickerI18n(buildDatePickerI18n())
                .withFormatLocale(TranslationProvider.getLocale())
                .withDateRangeLocalizerFunction {
                    when (it) {
                        SimpleDateRanges.TODAY       -> DateTimeKey.TODAY.get()
                        SimpleDateRanges.DAY         -> DateTimeKey.DAY.get()
                        SimpleDateRanges.WEEK        -> DateTimeKey.WEEK.get()
                        SimpleDateRanges.MONTH       -> DateTimeKey.MONTH.get()
                        SimpleDateRanges.QUARTER     -> DateTimeKey.QUARTER.get()
                        SimpleDateRanges.HALF_YEAR   -> DateTimeKey.HALF_YEAR.get()
                        SimpleDateRanges.YEAR        -> DateTimeKey.YEAR.get()
                        SimpleDateRanges.FREE        -> DateTimeKey.FREE.get()
                        ExtendedSimpleDateRanges.ALL -> DateTimeKey.ALL.get()
                        else                         -> it.defaultDescription
                    }
                }.apply {
                    setStartLabel(DateTimeKey.START.get())
                    setEndLabel(DateTimeKey.END.get())
                    setDateRangeOptionsLabel(DateTimeKey.PERIOD.get())
                }

    private fun buildDateRangeModel() = DateRangeModel(LocalDate.now(), LocalDate.now(), SimpleDateRanges.TODAY)
```

### Expected behavior

The date range in the overlay button is formatted accordingly to the provided locale.

### Actual behavior

<img width="528" alt="CleanShot 2024-08-02 at 22 51 27@2x" src="https://github.com/user-attachments/assets/69a3fbb8-e830-479b-8b7e-b2c498cbe878">

Locale is set to EN, for the Start/End fields it is applied correctly. But not for the overlay button. I tried to debug it, the method to set this text is called multiple times, the ~3 times with EN and then 2 times with DE, which is also the end result. 

### Additional information

vaadin 24.4.7

**Comment by AB-xdev** [comment]
I had a quick look and as far as I can tell the problem here is that it always uses the client side locale to format the text:

https://github.com/xdev-software/vaadin-date-range-picker/blob/c052ebcac0f1536431bf07621663b49df8b85735/vaadin-date-range-picker/src/main/java/software/xdev/vaadin/daterange_picker/ui/DateRangePicker.java#L259

I will provide a fix for that, so that it only uses the client-side locale when no other locale is set.
