### ISSUE TITLE
Add the option to use other Datepickers / Add Datepicker supplier

### ISSUE THREAD

**Issue by AB-xdev** [xdev-software/vaadin-date-range-picker#97]
Currently the Vaadin Datepicker is very limited.
For example it doesn't support a date format → https://github.com/vaadin/flow-components/issues/911

However there are some solutions for this problem:
* [EnhancedDatePicker](https://github.com/vaadin-component-factory/enhanced-date-picker) which like the normal Datepicker also extends from ``GeneratedDatePicker`` (and is now licensed under Apache 2)
* https://cookbook.vaadin.com/date-picker-pattern

To make them work a supplier (with ``GeneratedDatePicker``) or two - for ``start`` and ``end`` - is required.

**Comment by JohannesRabauer** [comment]
The function `setDateFormat` is now available in the Vaadin Datepicker.
Please confirm my interpretation of your suggestion:
You want to implement, for example, one funciton with `withDatePicker(GeneratedDatePicker datePicker)` with which you can change the used DatePicker?
Is this still relevant?

**Comment by AB-xdev** [comment]
No, can be closed. Function was implemented by ``setDateFormat``. Can be reopened on demand.
